"""
data_loader.py

Loads portfolio data generated by generate_portfolio_data.py
and converts it into NumPy arrays for optimization.

Output
------
portfolio_data = {
    "tickers": ...,
    "asset_classes": ...,
    "mu": ...,
    "Sigma": ...,
    "yield": ...,
    "drawdown": ...,
    "cost": ...
}
"""
import os
import sys

from pathlib import Path

import numpy as np
import pandas as pd

PROJECT_ROOT = os.path.dirname(
    os.path.dirname(os.path.abspath(__file__))
)

if PROJECT_ROOT not in sys.path:
    sys.path.insert(0, PROJECT_ROOT)

from config import *

from config.settings import Portfolio_Data_File
from config.assets import get_group_mapping


def load_portfolio_data(excel_file=None):
    """
    Read Portfolio_Data.xlsx and return optimization-ready data.

    Returns
    -------
    dict
    """

    if excel_file is None:
        excel_file = Portfolio_Data_File

    excel_file = Path(excel_file)

    if not excel_file.exists():
        raise FileNotFoundError(
            f"\nPortfolio data not found:\n{excel_file}\n"
            "Run generate_portfolio_data.py first."
        )

    asset_df = pd.read_excel(
        excel_file,
        sheet_name="Asset_Data",
    )

    covariance_df = pd.read_excel(
        excel_file,
        sheet_name="Covariance",
        index_col=0,
    )

    # Keep covariance ordering identical to Asset_Data ordering.
    tickers = asset_df["Ticker"].tolist()
    missing = [t for t in tickers if t not in covariance_df.index]
    if missing:
        raise ValueError(f"Covariance sheet is missing tickers: {missing}")
    covariance_df = covariance_df.loc[tickers, tickers]

    portfolio_data = {

        "tickers":
            asset_df["Ticker"].tolist(),

        "asset_classes":
            asset_df["AssetClass"].tolist(),

        "groups":
            [get_group_mapping()[t] for t in tickers],

        "mu":
            asset_df["ExpectedReturn"].to_numpy(dtype=float),

        "yield":
            asset_df["DividendYield"].to_numpy(dtype=float),

        "drawdown":
            asset_df["MaxDrawdown"].to_numpy(dtype=float),

        "cost":
            asset_df["TransactionCost"].to_numpy(dtype=float),

        "volatility":
            asset_df["AnnualVolatility"].to_numpy(dtype=float),

        "Sigma":
            covariance_df.to_numpy(dtype=float),

        "N":
            len(asset_df)

    }

    return portfolio_data


def get_sector_indices(asset_classes):
    """
    Convert asset classes into index lists.

    Example
    -------
    {
        "Equity":[0,1,2],
        "Bond":[3,4],
        ...
    }
    """

    sectors = {}

    for idx, sector in enumerate(asset_classes):

        sectors.setdefault(sector, []).append(idx)

    return sectors


def portfolio_dataframe(weights, portfolio_data):
    """
    Convert optimization weights into a DataFrame.
    """

    df = pd.DataFrame({

        "Ticker":
            portfolio_data["tickers"],

        "AssetClass":
            portfolio_data["asset_classes"],

        "Weight":
            np.round(weights, 6)

    })

    df = df[df["Weight"] > 1e-6]

    df = df.sort_values(
        "Weight",
        ascending=False,
    )

    df.reset_index(
        drop=True,
        inplace=True,
    )

    return df


def print_summary(portfolio_data):
    """
    Print dataset summary.
    """

    print("\nPortfolio Dataset")
    print("---------------------------")
    print(f"Assets          : {portfolio_data['N']}")
    print(f"Expected Return : {portfolio_data['mu'].shape}")
    print(f"Covariance      : {portfolio_data['Sigma'].shape}")
    print(f"Dividend Yield  : {portfolio_data['yield'].shape}")
    print(f"Drawdown        : {portfolio_data['drawdown'].shape}")
    print(f"TransactionCost : {portfolio_data['cost'].shape}")


if __name__ == "__main__":

    data = load_portfolio_data()

    print_summary(data)

    print()

    print(portfolio_dataframe(
        np.zeros(data["N"]),
        data,
    ))